### ISSUE TITLE
Error executing octopress after plugin install

### ISSUE THREAD

**Issue by UnclePetros** [octopress/multilingual#22]
After plugin install I receive the following error when execute "octopress --help" :

```
C:/Ruby200/lib/ruby/gems/2.0.0/gems/octopress-multilingual-1.2.0/lib/octopress-m
ultilingual/jekyll.rb:85:in `<class:Post>': undefined method `template' for clas
s `Jekyll::Post' (NameError)
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/octopress-multilingual-1.2.0/li
b/octopress-multilingual/jekyll.rb:84:in `<module:Jekyll>'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/octopress-multilingual-1.2.0/li
b/octopress-multilingual/jekyll.rb:1:in `<top (required)>'
        from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/octopress-multilingual-1.2.0/li
b/octopress-multilingual.rb:9:in `<top (required)>'
        from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:i
n `require'
        from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:i
n `rescue in require'
        from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:i
n `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/octopress-3.0.11/lib/octopress.
rb:99:in `block in require_blessed_gems'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/octopress-3.0.11/lib/octopress.
rb:97:in `each'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/octopress-3.0.11/lib/octopress.
rb:97:in `require_blessed_gems'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/octopress-3.0.11/lib/octopress.
rb:106:in `require_gems'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/octopress-3.0.11/lib/octopress.
rb:133:in `<top (required)>'
        from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in
 `require'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/octopress-3.0.11/bin/octopress:
6:in `<top (required)>'
        from C:/Ruby200/bin/octopress:23:in `load'
        from C:/Ruby200/bin/octopress:23:in `<main>'
```

Uninstalling octopress-multilingual solve the issue.

**Comment by ndim** [comment]
It appears that `jekyll` removed some code `octopress-multilingual` relies on (i.e. `Jekyll::Page::template`) in 2015-10. The last commit to `octopress-multilingual` was in 2015-05, so that explains the incompatibility between 2015-12 `octopress-multilingual` and `jekyll`.

**Comment by ndim** [comment]
A quick fix might be to switch back to a pre-3.0 version of Jekyll if you do not rely on Jekyll >= 3.0.0 in other parts of your code.

I have had some success adding to the `Gemfile`

``` ruby
gem 'jekyll', '< 3.0.0'
```

and running `bundle install`/`bundle update`.
